site_name: DiscordTel
site_url: https://discordtel.austinhuang.me
repo_url: https://github.com/austinhuang0131/discordtel
edit_uri: blob/readthedocs/docs/
theme:
  name: readthedocs
nav:
  - 'Customer Support Guide': ./docs/csg.md
